//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityTransitApp.WPSilverlight.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityTransitApp.WPSilverlight.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string AppDistanceUnit {
            get {
                return ResourceManager.GetString("AppDistanceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP SCHEDULE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app accesses your phone&apos;s location to show nearby stops on map and plan trips. Do you allow location services for the app?.
        /// </summary>
        public static string AppLocationConsent {
            get {
                return ResourceManager.GetString("AppLocationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t allow.
        /// </summary>
        public static string AppLocationConsentDisable {
            get {
                return ResourceManager.GetString("AppLocationConsentDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string AppLocationConsentEnable {
            get {
                return ResourceManager.GetString("AppLocationConsentEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services.
        /// </summary>
        public static string AppLocationConsentTitle {
            get {
                return ResourceManager.GetString("AppLocationConsentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string CardinalEast {
            get {
                return ResourceManager.GetString("CardinalEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string CardinalNorth {
            get {
                return ResourceManager.GetString("CardinalNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North-East.
        /// </summary>
        public static string CardinalNorthEast {
            get {
                return ResourceManager.GetString("CardinalNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North-West.
        /// </summary>
        public static string CardinalNorthWest {
            get {
                return ResourceManager.GetString("CardinalNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string CardinalSouth {
            get {
                return ResourceManager.GetString("CardinalSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South-East.
        /// </summary>
        public static string CardinalSouthEast {
            get {
                return ResourceManager.GetString("CardinalSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South-West.
        /// </summary>
        public static string CardinalSouthWest {
            get {
                return ResourceManager.GetString("CardinalSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string CardinalWest {
            get {
                return ResourceManager.GetString("CardinalWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrive.
        /// </summary>
        public static string DateTimeArrive {
            get {
                return ResourceManager.GetString("DateTimeArrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart.
        /// </summary>
        public static string DateTimeDeparture {
            get {
                return ResourceManager.GetString("DateTimeDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string DateTimeToday {
            get {
                return ResourceManager.GetString("DateTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string DateTimeTomorrow {
            get {
                return ResourceManager.GetString("DateTimeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing downloaded files!.
        /// </summary>
        public static string DownloadDecompress {
            get {
                return ResourceManager.GetString("DownloadDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database loading!.
        /// </summary>
        public static string DownloadLoadDB {
            get {
                return ResourceManager.GetString("DownloadLoadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is unavailable. Check if you are connected to the network..
        /// </summary>
        public static string DownloadNoAccess {
            get {
                return ResourceManager.GetString("DownloadNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded:.
        /// </summary>
        public static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is ready!.
        /// </summary>
        public static string DownloadReady {
            get {
                return ResourceManager.GetString("DownloadReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for database loading..
        /// </summary>
        public static string DownloadWaitDB {
            get {
                return ResourceManager.GetString("DownloadWaitDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this page?.
        /// </summary>
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows departing vehicles from a selected stop/station and from stops nearby.
        ///On the right you can see how many minutes left until the next vehicle arrives.
        ///If you tap on a bar of a stop/station you can view it on the map..
        /// </summary>
        public static string HelpStop {
            get {
                return ResourceManager.GetString("HelpStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows the departure times of the selected route from a selected stop/station on a selected day.
        ///You can see the departure times in the main part of the page grouped by hours.
        ///If you tap on a departure time you can access the selected trip&apos;s own page.
        ///If you tap on the date (top line) you can choose another day to display.
        ///If you tap on the route label (second line) the page will show departure times of vehicles traveling in the opposite direction.
        ///If you tap on the stop label you can choose a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpTimetable {
            get {
                return ResourceManager.GetString("HelpTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows the arrival times of a selected trip.
        ///You can find transfers by clicking on a stop from the list.
        ///You can select next or previous trips by swiping or selecting it from the top bar.
        ///Also if you tap on the destination label the page will show the next trip to the opposite direction..
        /// </summary>
        public static string HelpTrip {
            get {
                return ResourceManager.GetString("HelpTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a destination or a stop..
        /// </summary>
        public static string HistorySelectText {
            get {
                return ResourceManager.GetString("HistorySelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST VIEWED.
        /// </summary>
        public static string HistoryStopsLabel {
            get {
                return ResourceManager.GetString("HistoryStopsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string MainContextDown {
            get {
                return ResourceManager.GetString("MainContextDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string MainContextPin {
            get {
                return ResourceManager.GetString("MainContextPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string MainContextRemove {
            get {
                return ResourceManager.GetString("MainContextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string MainContextUp {
            get {
                return ResourceManager.GetString("MainContextUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to download the schedule database to use the application. Tap to download..
        /// </summary>
        public static string MainDownloadDescr {
            get {
                return ResourceManager.GetString("MainDownloadDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update is done. You have to restart the application now..
        /// </summary>
        public static string MainDownloadDone {
            get {
                return ResourceManager.GetString("MainDownloadDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress..
        /// </summary>
        public static string MainDownloadProgress {
            get {
                return ResourceManager.GetString("MainDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string MainDownloadTitle {
            get {
                return ResourceManager.GetString("MainDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAVORITES.
        /// </summary>
        public static string MainFavorites {
            get {
                return ResourceManager.GetString("MainFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        public static string MainHistory {
            get {
                return ResourceManager.GetString("MainHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search update.
        /// </summary>
        public static string MainMenuCheckUpdate {
            get {
                return ResourceManager.GetString("MainMenuCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planning options.
        /// </summary>
        public static string MainMenuFilter {
            get {
                return ResourceManager.GetString("MainMenuFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on map.
        /// </summary>
        public static string MainMenuMap {
            get {
                return ResourceManager.GetString("MainMenuMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string MainMenuNear {
            get {
                return ResourceManager.GetString("MainMenuNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase offline planning.
        /// </summary>
        public static string MainMenuOfflinePlanning {
            get {
                return ResourceManager.GetString("MainMenuOfflinePlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MainMenuSearch {
            get {
                return ResourceManager.GetString("MainMenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainMenuSettings {
            get {
                return ResourceManager.GetString("MainMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string MainMenuUpdate {
            get {
                return ResourceManager.GetString("MainMenuUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearest stop.
        /// </summary>
        public static string MainNearest {
            get {
                return ResourceManager.GetString("MainNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data connection..
        /// </summary>
        public static string MainProgressNoInternet {
            get {
                return ResourceManager.GetString("MainProgressNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is up to date..
        /// </summary>
        public static string MainProgressNoUpdate {
            get {
                return ResourceManager.GetString("MainProgressNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENTLY VIEWED.
        /// </summary>
        public static string MainRecent {
            get {
                return ResourceManager.GetString("MainRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorites..
        /// </summary>
        public static string MainTabNoFavorites {
            get {
                return ResourceManager.GetString("MainTabNoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANNING.
        /// </summary>
        public static string MainTabPlanning {
            get {
                return ResourceManager.GetString("MainTabPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE.
        /// </summary>
        public static string MainTabSchedules {
            get {
                return ResourceManager.GetString("MainTabSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schedule is out of date, update is available..
        /// </summary>
        public static string MainTopOutOfDate {
            get {
                return ResourceManager.GetString("MainTopOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NearCancelButton {
            get {
                return ResourceManager.GetString("NearCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services.
        /// </summary>
        public static string NearLocationServices {
            get {
                return ResourceManager.GetString("NearLocationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NearLocButton {
            get {
                return ResourceManager.GetString("NearLocButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enable location services in settings to use this function..
        /// </summary>
        public static string NearLocDescription {
            get {
                return ResourceManager.GetString("NearLocDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance &lt; .
        /// </summary>
        public static string NearPageDistance {
            get {
                return ResourceManager.GetString("NearPageDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby stops.
        /// </summary>
        public static string NearPageTitle {
            get {
                return ResourceManager.GetString("NearPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service unavailable.
        /// </summary>
        public static string NearUnavailable {
            get {
                return ResourceManager.GetString("NearUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string NearUnavailableButton {
            get {
                return ResourceManager.GetString("NearUnavailableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are unavailable, searching for nearby stops is not possible..
        /// </summary>
        public static string NearUnavailableDescr {
            get {
                return ResourceManager.GetString("NearUnavailableDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % ➤ %.
        /// </summary>
        public static string PlanDetailsRoute {
            get {
                return ResourceManager.GetString("PlanDetailsRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route details.
        /// </summary>
        public static string PlanDetailsTitle {
            get {
                return ResourceManager.GetString("PlanDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw map.
        /// </summary>
        public static string PlanDetailsToMap {
            get {
                return ResourceManager.GetString("PlanDetailsToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % stop/|s/.
        /// </summary>
        public static string PlanDetailsTrip {
            get {
                return ResourceManager.GetString("PlanDetailsTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait % minute/|s/.
        /// </summary>
        public static string PlanDetailsWait {
            get {
                return ResourceManager.GetString("PlanDetailsWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to walk % /foot|feet/.
        /// </summary>
        public static string PlanDetailsWalk {
            get {
                return ResourceManager.GetString("PlanDetailsWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string PlaningBtn {
            get {
                return ResourceManager.GetString("PlaningBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string PlanItemAt {
            get {
                return ResourceManager.GetString("PlanItemAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take off from line.
        /// </summary>
        public static string PlanItemFinish1 {
            get {
                return ResourceManager.GetString("PlanItemFinish1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and arrive at your destination.
        /// </summary>
        public static string PlanItemFinish2 {
            get {
                return ResourceManager.GetString("PlanItemFinish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then walk to the transfer.
        /// </summary>
        public static string PlanItemMidFinish2 {
            get {
                return ResourceManager.GetString("PlanItemMidFinish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer to the folllowing vehicle.
        /// </summary>
        public static string PlanItemMidStart1 {
            get {
                return ResourceManager.GetString("PlanItemMidStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take the following vehicle.
        /// </summary>
        public static string PlanItemStart1 {
            get {
                return ResourceManager.GetString("PlanItemStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and travel % stops.
        /// </summary>
        public static string PlanItemStart2 {
            get {
                return ResourceManager.GetString("PlanItemStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string PlanItemTo {
            get {
                return ResourceManager.GetString("PlanItemTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map !.
        /// </summary>
        public static string PlanMenuMap {
            get {
                return ResourceManager.GetString("PlanMenuMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planning has failed, please try again..
        /// </summary>
        public static string PlanningError {
            get {
                return ResourceManager.GetString("PlanningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az útvonaltervezés az alkalmazás ezen verziójában nem elérhető..
        /// </summary>
        public static string PlanningFreeVersion {
            get {
                return ResourceManager.GetString("PlanningFreeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot start a new planning while the previous planning is in progress..
        /// </summary>
        public static string PlanningInProgress {
            get {
                return ResourceManager.GetString("PlanningInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs internetkapcsolat. Jelenleg az útvonaltervező funkció csak aktív interneteléréssel működik. Ha szeretne internetkapcsolat nélkül is útvonalat tervezni, akkor később koppintson a menüben az &apos;Offline útvonaltervezés&apos; menüpontra és vásárolja meg a funkciót..
        /// </summary>
        public static string PlanningNoAccess {
            get {
                return ResourceManager.GetString("PlanningNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route found between selected stops..
        /// </summary>
        public static string PlanningNoResult {
            get {
                return ResourceManager.GetString("PlanningNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a start stop..
        /// </summary>
        public static string PlanningSourceEmpty {
            get {
                return ResourceManager.GetString("PlanningSourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a destination stop..
        /// </summary>
        public static string PlanningTargetEmpty {
            get {
                return ResourceManager.GetString("PlanningTargetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning complete.
        /// </summary>
        public static string PlanningTimeLabel {
            get {
                return ResourceManager.GetString("PlanningTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depart at .
        /// </summary>
        public static string PlanningTopHeaderLine1 {
            get {
                return ResourceManager.GetString("PlanningTopHeaderLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , arrive at .
        /// </summary>
        public static string PlanningTopHeaderLine2 {
            get {
                return ResourceManager.GetString("PlanningTopHeaderLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az útvonaltervezés funkció jelenleg nem érhető el, mert Ön alkalmazás próba verzióját használja és a próbaidő lejárt. A funkció használatához vásárolja meg a teljes verziót az Áruházból!.
        /// </summary>
        public static string PlanningTrialExpired {
            get {
                return ResourceManager.GetString("PlanningTrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk.
        /// </summary>
        public static string PlanningWalk {
            get {
                return ResourceManager.GetString("PlanningWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aspects of planning.
        /// </summary>
        public static string PlanSettingsAspect {
            get {
                return ResourceManager.GetString("PlanSettingsAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select at least one aspect..
        /// </summary>
        public static string PlanSettingsCheckedType {
            get {
                return ResourceManager.GetString("PlanSettingsCheckedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrier-free settings.
        /// </summary>
        public static string PlanSettingsDisabled {
            get {
                return ResourceManager.GetString("PlanSettingsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A BKK weboldalán kiadott hivatalos adatbázisban sajnos hiányosak az akadálymentes megállókkal kapcsolatos információk, ezért nem javasolt ennek a feltételnek a bejelölése, mert a tervezés valószínűleg nem fog útvonalat találni. Továbbra is be szeretné jelölni?.
        /// </summary>
        public static string PlanSettingsDisabledStopError {
            get {
                return ResourceManager.GetString("PlanSettingsDisabledStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only barrier-free stops.
        /// </summary>
        public static string PlanSettingsDisabledStops {
            get {
                return ResourceManager.GetString("PlanSettingsDisabledStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only barrier-free vehicles.
        /// </summary>
        public static string PlanSettingsDisabledVehicles {
            get {
                return ResourceManager.GetString("PlanSettingsDisabledVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fast.
        /// </summary>
        public static string PlanSettingsFastWalk {
            get {
                return ResourceManager.GetString("PlanSettingsFastWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.2 mph.
        /// </summary>
        public static string PlanSettingsFastWalkValue {
            get {
                return ResourceManager.GetString("PlanSettingsFastWalkValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planner will execute planning considering the following aspects. If you check more then more planning will run at the same time, this can result longer planning if your device has few CPU cores.
        ///The different results will apear in lines, ordered by relevance..
        /// </summary>
        public static string PlanSettingsHelp {
            get {
                return ResourceManager.GetString("PlanSettingsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string PlanSettingsNormalWalk {
            get {
                return ResourceManager.GetString("PlanSettingsNormalWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1 mph.
        /// </summary>
        public static string PlanSettingsNormalWalkValue {
            get {
                return ResourceManager.GetString("PlanSettingsNormalWalkValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan settings.
        /// </summary>
        public static string PlanSettingsPageTitle {
            get {
                return ResourceManager.GetString("PlanSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slow.
        /// </summary>
        public static string PlanSettingsSlowWalk {
            get {
                return ResourceManager.GetString("PlanSettingsSlowWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.9 mph.
        /// </summary>
        public static string PlanSettingsSlowWalkValue {
            get {
                return ResourceManager.GetString("PlanSettingsSlowWalkValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string PlanSettingsTime {
            get {
                return ResourceManager.GetString("PlanSettingsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer count.
        /// </summary>
        public static string PlanSettingsTransfer {
            get {
                return ResourceManager.GetString("PlanSettingsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled vehicle types for the result.
        /// </summary>
        public static string PlanSettingsVehicles {
            get {
                return ResourceManager.GetString("PlanSettingsVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking distance.
        /// </summary>
        public static string PlanSettingsWalk {
            get {
                return ResourceManager.GetString("PlanSettingsWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of walking.
        /// </summary>
        public static string PlanSettingsWalkSpeed {
            get {
                return ResourceManager.GetString("PlanSettingsWalkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minute/|s/.
        /// </summary>
        public static string PlanTimeLabel {
            get {
                return ResourceManager.GetString("PlanTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  transfer/|s/.
        /// </summary>
        public static string PlanTransferLabel {
            get {
                return ResourceManager.GetString("PlanTransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ft walk.
        /// </summary>
        public static string PlanWalkLabel {
            get {
                return ResourceManager.GetString("PlanWalkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string RouteMenuCancel {
            get {
                return ResourceManager.GetString("RouteMenuCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string RouteMenuOK {
            get {
                return ResourceManager.GetString("RouteMenuOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of service.
        /// </summary>
        public static string RoutePanelOutOfService {
            get {
                return ResourceManager.GetString("RoutePanelOutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RouteStopFromPost {
            get {
                return ResourceManager.GetString("RouteStopFromPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from .
        /// </summary>
        public static string RouteStopFromPre {
            get {
                return ResourceManager.GetString("RouteStopFromPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RouteStopToPost {
            get {
                return ResourceManager.GetString("RouteStopToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to .
        /// </summary>
        public static string RouteStopToPre {
            get {
                return ResourceManager.GetString("RouteStopToPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subway.
        /// </summary>
        public static string SearchCatLabel1 {
            get {
                return ResourceManager.GetString("SearchCatLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail.
        /// </summary>
        public static string SearchCatLabel2 {
            get {
                return ResourceManager.GetString("SearchCatLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tram.
        /// </summary>
        public static string SearchCatLabel3 {
            get {
                return ResourceManager.GetString("SearchCatLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string SearchCatLabel4 {
            get {
                return ResourceManager.GetString("SearchCatLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string SearchCatLabel5 {
            get {
                return ResourceManager.GetString("SearchCatLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night bus.
        /// </summary>
        public static string SearchCatLabel6 {
            get {
                return ResourceManager.GetString("SearchCatLabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a vehicle line or a stop name..
        /// </summary>
        public static string SearchDefault {
            get {
                return ResourceManager.GetString("SearchDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic check for nearby stops.
        /// </summary>
        public static string SettingsAutoNear {
            get {
                return ResourceManager.GetString("SettingsAutoNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enable this function the application will use location services each time it starts..
        /// </summary>
        public static string SettingsAutoNearLabel {
            get {
                return ResourceManager.GetString("SettingsAutoNearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates automatically.
        /// </summary>
        public static string SettingsAutoUpdate {
            get {
                return ResourceManager.GetString("SettingsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete search history?.
        /// </summary>
        public static string SettingsClearConfirm {
            get {
                return ResourceManager.GetString("SettingsClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete history.
        /// </summary>
        public static string SettingsClearHistory {
            get {
                return ResourceManager.GetString("SettingsClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services.
        /// </summary>
        public static string SettingsLocationServices {
            get {
                return ResourceManager.GetString("SettingsLocationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string SettingsNo {
            get {
                return ResourceManager.GetString("SettingsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SettingsOff {
            get {
                return ResourceManager.GetString("SettingsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SettingsOn {
            get {
                return ResourceManager.GetString("SettingsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every day.
        /// </summary>
        public static string SettingsPerDay {
            get {
                return ResourceManager.GetString("SettingsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every week.
        /// </summary>
        public static string SettingsPerWeek {
            get {
                return ResourceManager.GetString("SettingsPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every % days.
        /// </summary>
        public static string SettingsPerXDay {
            get {
                return ResourceManager.GetString("SettingsPerXDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new theme will be displayed after restarting the application..
        /// </summary>
        public static string SettingsRestartRequired {
            get {
                return ResourceManager.GetString("SettingsRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline barrier-free vehicles..
        /// </summary>
        public static string SettingsUnderline {
            get {
                return ResourceManager.GetString("SettingsUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the schedule the times for barrier-free vehicles will appear underlined..
        /// </summary>
        public static string SettingsUnderlineDescr {
            get {
                return ResourceManager.GetString("SettingsUnderlineDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check frequency.
        /// </summary>
        public static string SettingsUpdateInterval {
            get {
                return ResourceManager.GetString("SettingsUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string SettingsYes {
            get {
                return ResourceManager.GetString("SettingsYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance: .
        /// </summary>
        public static string StopDistance {
            get {
                return ResourceManager.GetString("StopDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departures after %.
        /// </summary>
        public static string StopMapDepartures {
            get {
                return ResourceManager.GetString("StopMapDepartures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance is % (% minute/|s/).
        /// </summary>
        public static string StopMapDistance {
            get {
                return ResourceManager.GetString("StopMapDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you arrive here.
        /// </summary>
        public static string StopMapPosition {
            get {
                return ResourceManager.GetString("StopMapPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes).
        /// </summary>
        public static string StopMinute {
            get {
                return ResourceManager.GetString("StopMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to near transfers.
        /// </summary>
        public static string StopNearBtn {
            get {
                return ResourceManager.GetString("StopNearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no additional transfers near this stop..
        /// </summary>
        public static string StopNoTransfers {
            get {
                return ResourceManager.GetString("StopNoTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a stop!.
        /// </summary>
        public static string StopPickerChoose {
            get {
                return ResourceManager.GetString("StopPickerChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEAR STOPS.
        /// </summary>
        public static string StopTransfersCategory {
            get {
                return ResourceManager.GetString("StopTransfersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfers at .
        /// </summary>
        public static string StopTransfersLabel {
            get {
                return ResourceManager.GetString("StopTransfersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string StringMinute {
            get {
                return ResourceManager.GetString("StringMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string StringMinutePl {
            get {
                return ResourceManager.GetString("StringMinutePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already pinned this..
        /// </summary>
        public static string TileAlreadyDone {
            get {
                return ResourceManager.GetString("TileAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a stop!.
        /// </summary>
        public static string TimetableChooseStop {
            get {
                return ResourceManager.GetString("TimetableChooseStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TimetableDirectionPost {
            get {
                return ResourceManager.GetString("TimetableDirectionPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string TimetableDirectionPre {
            get {
                return ResourceManager.GetString("TimetableDirectionPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TimetableFromPost {
            get {
                return ResourceManager.GetString("TimetableFromPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string TimetableFromPre {
            get {
                return ResourceManager.GetString("TimetableFromPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TimeTableLabelPost {
            get {
                return ResourceManager.GetString("TimeTableLabelPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add favs.
        /// </summary>
        public static string TimetableMenuAddFavs {
            get {
                return ResourceManager.GetString("TimetableMenuAddFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string TimetableMenuPin {
            get {
                return ResourceManager.GetString("TimetableMenuPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next day.
        /// </summary>
        public static string TimeTableNextDay {
            get {
                return ResourceManager.GetString("TimeTableNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous day.
        /// </summary>
        public static string TimeTablePreviousDay {
            get {
                return ResourceManager.GetString("TimeTablePreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected day.
        /// </summary>
        public static string TimeTableThisDay {
            get {
                return ResourceManager.GetString("TimeTableThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TimeTableToday {
            get {
                return ResourceManager.GetString("TimeTableToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string TimeTableTomorrow {
            get {
                return ResourceManager.GetString("TimeTableTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string TimeTableYesterday {
            get {
                return ResourceManager.GetString("TimeTableYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can add a timetable to your favorites by tapping the icon at the application bar. Next time you will see the timetable on the start page of the application..
        /// </summary>
        public static string TipAddFavs {
            get {
                return ResourceManager.GetString("TipAddFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: To pin a timetable to the start screen tap and hold on the selected item..
        /// </summary>
        public static string TipLiveTile {
            get {
                return ResourceManager.GetString("TipLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on map.
        /// </summary>
        public static string TripMenuMap {
            get {
                return ResourceManager.GetString("TripMenuMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timetable.
        /// </summary>
        public static string TripMenuTimetable {
            get {
                return ResourceManager.GetString("TripMenuTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop distance.
        /// </summary>
        public static string TripStopDistance {
            get {
                return ResourceManager.GetString("TripStopDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to → full timetable.
        /// </summary>
        public static string TripTopButton {
            get {
                return ResourceManager.GetString("TripTopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer walk distance.
        /// </summary>
        public static string TripTransferDistance {
            get {
                return ResourceManager.GetString("TripTransferDistance", resourceCulture);
            }
        }
    }
}
